# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title: 'Daniel Henriques' 
tagline: 'Software Developer'
description: '' 
url: 'http://henrid.com'
baseurl: '/'

author:
  name:           'Daniel Henriques'
  url: 'http://henrid.com'           

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/henrid/henrid.github.io
